name: Release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release on PyPI
    runs-on: ubuntu-latest

    environment:
      name: PyPI
      url: https://pypi.org/project/odoo-orm/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Check version consistency
        run: |
          [[ "$(uv version)" == "$(git describe --tags)" ]]

      - name: Build project
        run: uv build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish
