name: Release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release on PyPI
    runs-on: ubuntu-latest

    environment:
      name: PyPI
      url: https://pypi.org/project/odoo-orm/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.11
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Check version consistency
        run: |
          [[ "$(poetry version -s)" == "$(git describe --tags)" ]]

      - name: Build project
        run: poetry build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish -u __token__ -p "$PYPI_TOKEN"
